name = input("Enter your name = ")
surname = input("Entter your surname = ")
print (name, surname)
a = int(input("Enter your a integer = "))
b = int(input("Enter your b integer = "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)
print(a%b)
print(a<b)
print(a>b)
print(a<=b)
print(a!=b)
print(a==b)
